pipeline {
    agent any

    environment {
        GOROOT = "/usr/local/go"
        GOPATH = "/go"
        PATH = "${GOROOT}/bin:${GOPATH}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
            
                git 'https://github.com/siva27122003/Build_binary_file_Task_1.git'
            }
        }

        stage('Prepare Modules') {
            steps {
                dir('Jenkins_pipeline/src') {
                    sh '''
                        if [ ! -f go.mod ]; then
                            go mod init buildbinarytask
                        fi
                        go mod tidy
                    '''
                }
            }
        }

        stage('Build') {
            steps {
                dir('Jenkins_pipeline/src') {
                    sh 'go build -o main main.go'
                }
            }
        }

        stage('Run Binary') {
            steps {
                dir('Jenkins_pipeline/src') {
                    sh 'chmod +x main'
                    sh './main'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Jenkins_pipeline/src') {
                    sh 'go test ./...'
                }
            }
        }
    }
}
