pipeline {
    agent any

    environment {
        GOROOT = "/usr/local/go"
        GOPATH = "/go"
        PATH = "${GOROOT}/bin:${GOPATH}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/siva27122003/Build_binary_file_Task_1.git'
            }
        }

        stage('Build') {
            steps {
                dir('Jenkins_pipeline/src') {
                    sh 'go build -o main main.go'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Jenkins_pipeline/src') {
                    sh 'go test ./...'
                }
            }
        }
    }
}
