pipeline {
    agent any

    environment {
        GOROOT = "/usr/local/go"
        GOPATH = "/go"
        PATH = "${GOROOT}/bin:${GOPATH}/bin:${env.PATH}"
    }

    stages {
        stage('Prepare Modules') {
            steps {
                dir('Jenkins_pipeline/src') {
                    sh '''
                        if [ ! -f go.mod ]; then
                            go mod init buildbinarytask
                        fi
                        go mod tidy
                    '''
                }
            }
        }

        stage('Build') {
            steps {
                dir('Jenkins_pipeline/src') {
                    sh 'go build -o main main.go'
                }
            }
        }

        stage('Run Binary') {
            steps {
                dir('Jenkins_pipeline/src') {
                    sh '''
                        chmod +x main
                        ./main 9876543210
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir('Jenkins_pipeline/src') {
                    sh 'go test ./...'
                }
            }
        }

        stage('Zip Build') {
            steps {
                sh '''
                    apt-get update
                    apt-get install zip 
                    mkdir -p artifact_output
                    cd Jenkins_pipeline/src
                    zip ../../artifact_output/phone_number_validate.zip main
                '''
            }
        }
        stage('Test parameter'){
            steps{
                echo " Build completed! build done by ${params.Build_by}"
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'artifact_output/phone_number_validate.zip', allowEmptyArchive: false
            }
        }
    }
}
