pipeline {
    agent any

    environment {
        DOCKERHUB_USER = "sivasankar123"
        DOCKERHUB_PASS = "Siva@2003"    // Ideally, store this as Jenkins secret and inject here
        IMAGE_NAME = "${DOCKERHUB_USER}/phone-number-validator"
        TAG = "latest"
    }

    stages {
        stage('Check Docker Access') {
            steps {
                sh 'docker --version'
                sh 'docker ps'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:${TAG} ."
            }
        }

        stage('Login to Docker Hub') {
            steps {
                // safer to avoid password in plain text in logs
                sh "echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin"
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${IMAGE_NAME}:${TAG}"
            }
        }
    }

    post {
        always {
            echo "Pipeline execution finished."
        }
    }
}
