pipeline {
    agent any

    tools {
        go 'Go 1.20'
    }

    stages {
        stage('Clone') {
            steps {
                git https://github.com/siva27122003/Build_binary_file_Task_1.git
            }
        }

        stage('Build') {
            steps {
                sh 'go build ./...'
            }
        }

        stage('Test') {
            steps {
                sh 'go test ./...'
            }
        }
    }
}
